### ISSUE TITLE
你好能分享一下你的数据集嘛

### ISSUE THREAD

**Issue by B1GGUN** [OldDriverJinx/reimplemention-of-Dual-PRNet#2]
你好能分享一下你的数据集嘛

**Comment by ZAX130** [comment]
> 

你点一下首页下面的RCN链接下载

**Comment by JinxLv** [comment]
> 你好能分享一下你的数据集嘛

We used the same training dataset (LPBA) as RCN (https://github.com/microsoft/Recursive-Cascaded-Networks), it could be found in their repository.
