### ISSUE TITLE
Dice

### ISSUE THREAD

**Issue by BTRFusion** [OldDriverJinx/reimplemention-of-Dual-PRNet#3]
Dear jinx,
Hi. Great work is done! Thank you for sharing this code.
I use the provided LPBA dataset and 'python train.py -g 0 --batch 1 -d datasets/brain.json -b DUAL -n 1 --round 10000 --epoch 10' to train the model.
When the number of steps reaches 5000, the score is 0.65;
When the number of steps reaches 15000, the score is 0.67;
After that, the training reached 60000 steps, which was still 0.67.
I can't reach the 0.778 and 0.831 given in the results.
I don't know why. Looking forward to your reply.

**Comment by OldDriverJinx** [comment]
Thanks for your attention. The 0.67  is the mean Dice based on 56 regions in LPBA, while the 0.831 is based on 7 regions, which are merged following the description of the Dual-PRNet. More details have already been listed on the main page of the repository.

**Comment by JinxLv** [comment]
> Dear jinx, Hi. Great work is done! Thank you for sharing this code. I use the provided LPBA dataset and 'python train.py -g 0 --batch 1 -d datasets/brain.json -b DUAL -n 1 --round 10000 --epoch 10' to train the model. When the number of steps reaches 5000, the score is 0.65; When the number of steps reaches 15000, the score is 0.67; After that, the training reached 60000 steps, which was still 0.67. I can't reach the 0.778 and 0.831 given in the results. I don't know why. Looking forward to your reply.

Thanks for your attention. The 0.67 is the mean Dice based on 56 regions in LPBA, while the 0.831 is based on 7 regions, which are merged following the description of the Dual-PRNet. More details have already been listed on the main page of the repository.
